# vim:ts=2:sw=2:et:ai:sts=2
---
- name: abort if distribution mismatch
  fail:
    msg: |
      distribution mismatch: {{ ansible_distribution_release }} !=
      {{ apt__distro }}. Set FORCE_APT_DIST_UPGRADE=1 to override.
  when:
    ansible_distribution_release != apt__distro and
    not lookup('env','FORCE_APT_DIST_UPGRADE')

- name: configure APT sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  register: _apt_sources

- name: configure custom APT sources
  template:
    src: sources.list.d.j2
    dest: '/etc/apt/sources.list.d/{{ item.name }}.list'
  loop: '{{ apt__custom_sources | d([]) }}'
  register: _apt_custom_sources

- name: configure installation of recommended packages
  template:
    src: 02recommends.j2
    dest: /etc/apt/apt.conf.d/02recommends

- name: update package lists
  apt:
    update_cache: yes
    cache_valid_time: '{{
      0 if _apt_custom_sources.changed or _apt_sources.changed else 3600 }}'

- name: update packages
  apt:
    upgrade: dist
    purge: '{{ apt__purge_removed }}'
  when: apt__run_upgrade

- name: remove unneeded packages
  apt:
    autoremove: yes
    purge: '{{ apt__purge_removed }}'
  when: apt__run_autoremove

- name: install packages
  apt:
    name: '{{ apt__packages_to_install }}'
    state: latest

- name: enable services
  service:
    name: '{{ item }}'
    enabled: yes
  loop: '{{ apt__services_to_enable | d([]) }}'

- name: start services
  service:
    name: '{{ item }}'
    state: started
  loop: '{{ apt__services_to_start | d([]) }}'
