# vim:ts=2:sw=2:et:ai:sts=2
---
- name: create {{ item.afile }}
  ansible.builtin.copy:
    dest: '{{ item.afile }}'
    content: '{{ item.content }}'
    mode: '{{ _a2_conffile_mode }}'
    owner: '{{ _a2_conffile_owner }}'
    group: '{{ _a2_conffile_group }}'
  when: item.content and item.present
  notify: '{{ item.notify }}'

- name: assert {{ item.afile }} state
  ansible.builtin.file:
    dest: '{{ item.afile }}'
    state: |-
      {{ 'file' if item.present else 'absent' }}
    mode: '{{ _a2_conffile_mode }}'
    owner: '{{ _a2_conffile_owner }}'
    group: '{{ _a2_conffile_group }}'
  notify: '{{ item.notify }}'

- name: run {{ item.ctlcmd }} {{ item.name }}
  ansible.builtin.command:
    argv: '{{ [item.ctlcmd, item.name] }}'
    creates: '{{ item.efile if item.enabled else omit }}'
    removes: '{{ item.efile if not item.enabled else omit }}'
  notify: '{{ item.notify }}'
