# vim:ts=2:sw=2:et:ai:sts=2
---
- name: install apache2
  package:
    name: apache2
    state: latest

- name: create log directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '{{ _a2_logdirs_mode }}'
    owner: '{{ _a2_logdirs_owner or "root" }}'
    group: '{{ _a2_logdirs_group or "adm" }}'
  with_items: '{{ _a2_logdirs }}'

- name: install ports.conf
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'
  notify: apache2__restart_apache2

- name: start and enable service
  service:
    name: apache2
    state: started
    enabled: true

- name: install ferm configuration
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.d/apache2.conf
    owner: root
    group: adm
    mode: '0644'
  notify: apache2__reload_ferm
  when: _a2_install_ferm_svc | bool

- name: install logrotate configuration
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/apache2
    owner: root
    group: root
    mode: '0644'
  notify: apache2__reload_ferm
  when: _a2_install_ferm_svc | bool

- name: install configuration fragments
  include_tasks: conf_fragment.yaml
  loop: '{{ _a2_fragments }}'
