# vim: sw=2:sts=2
---
- name: simple_bind__reload_bind
  ansible.builtin.service:
    name: bind9
    state: reloaded

- name: simple_bind__reload_ferm
  ansible.builtin.service:
    name: ferm
    state: reloaded
