# vim: sw=2:sts=2
---
- name: _tina_reload_bind
  ansible.builtin.service:
    name: bind9
    state: reloaded

- name: _tina_reload_ferm
  ansible.builtin.service:
    name: ferm
    state: reloaded
