# vim: sw=2:sts=2
---

- name: Install package
  ansible.builtin.package:
    name: bind9
    state: present

- name: Start and enable service
  block:
    - name: Start bind9
      ansible.builtin.service:
        name: bind9
        state: started
        enabled: true
  rescue:
    # systemd unit name changed in Debian bullseye.
    - name: Start named
      ansible.builtin.service:
        name: named
        state: started
        enabled: true

- name: Install configuration files
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: /etc/bind/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - named.conf
    - named.conf.options
    - named.conf.local
  notify: _tina_reload_bind

- name: Place ferm config file
  ansible.builtin.template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.d/bind.conf
    owner: root
    group: adm
    mode: '0644'
  notify: _tina_reload_ferm
  when: simple_bind__install_ferm_svc | bool
