# vim:ts=2:sw=2:et:ai:sts=2
---
extends: default
rules:
  comments:
    min-spaces-from-content: 1  # Required by ansible-lint
  comments-indentation: false  # Required by ansible-lint
  document-start: disable
  line-length:
    max: 80
  braces:
    min-spaces-inside: 0  # Required by ansible-lint
    max-spaces-inside: 1  # Required by ansible-lint
  octal-values:
    forbid-implicit-octal: true  # Required by ansible-lint
    forbid-explicit-octal: true  # Required by ansible-lint
