# vim:ts=2:sw=2:et:ai:sts=2
---

# Distribution aliases.
apt__distro_aliases:
  unstable: sid
  testing: forky
  stable: trixie
  oldstable: bookworm
  oldoldstable: bullseye

# Distribution information (vendor, version) indexed by name.
_apt_distro_name2info:
  # Debian
  sid: [debian, 999]
  duke: [debian, 15]
  forky: [debian, 14]
  trixie: [debian, 13]
  bookworm: [debian, 12]
  bullseye: [debian, 11]
  buster: [debian, 10]
  stretch: [debian, 9]
  jessie: [debian, 8]
  wheezy: [debian, 7]
  squeeze: [debian, 6]
  lenny: [debian, 5]
  etch: [debian, 4]
  sarge: [debian, 3.1]
  woody: [debian, 3.0]
  potato: [debian, 2.2]
  slink: [debian, 2.1]
  hamm: [debian, 2.0]
  bo: [debian, 1.3]
  rex: [debian, 1.2]
  buzz: [debian, 1.1]
  # Ubuntu
  warty: [ubuntu, 4.10]
  hoary: [ubuntu, 5.04]
  breezy: [ubuntu, 5.10]
  dapper: [ubuntu, 6.06]
  edgy: [ubuntu, 6.10]
  feisty: [ubuntu, 7.04]
  gutsy: [ubuntu, 7.10]
  hardy: [ubuntu, 8.04]
  intrepid: [ubuntu, 8.10]
  jaunty: [ubuntu, 9.04]
  karmic: [ubuntu, 9.10]
  lucid: [ubuntu, 10.04]
  maverick: [ubuntu, 10.10]
  natty: [ubuntu, 11.04]
  oneiric: [ubuntu, 11.10]
  precise: [ubuntu, 12.04]
  quantal: [ubuntu, 12.10]
  raring: [ubuntu, 13.04]
  saucy: [ubuntu, 13.10]
  trusty: [ubuntu, 14.04]
  utopic: [ubuntu, 14.10]
  vivid: [ubuntu, 15.04]
  wily: [ubuntu, 15.10]
  xenial: [ubuntu, 16.04]
  yakkety: [ubuntu, 16.10]
  zesty: [ubuntu, 17.04]
  artful: [ubuntu, 17.10]
  bionic: [ubuntu, 18.04]
  cosmic: [ubuntu, 18.10]
  disco: [ubuntu, 19.04]
  eoan: [ubuntu, 19.10]
  focal: [ubuntu, 20.04]
  groovy: [ubuntu, 20.10]
  hirsute: [ubuntu, 21.04]
  impish: [ubuntu, 21.10]
  jammy: [ubuntu, 22.04]
  kinetic: [ubuntu, 22.10]
  lunar: [ubuntu, 23.04]
  mantic: [ubuntu, 23.10]
  noble: [ubuntu, 24.04]
  oracular: [ubuntu, 24.10]
  plucky: [ubuntu, 25.04]

apt__default_distro: |-
  {{ apt__distro_aliases.get('stable') }}

## Computed properties for user-defined `apt__distro`.

apt__distro_name: |-
  {{ apt__distro_aliases.get(apt__distro, apt__distro) }}

_apt_distro_info: |-
  {{ _apt_distro_name2info.get(apt__distro_name, ['unknown', -1]) }}

apt__vendor: |-
  {{ _apt_distro_info[0] }}

apt__distro_ver: |-
  {{ _apt_distro_info[1] }}

apt__distro_is_unstable: |-
  {{ apt__distro_name == 'sid' }}

# Distributions with full support.
_apt_current_ubuntu_distros:
  - trusty
  - xenial
  - bionic
  - focal
  - jammy
  - noble
  - plucky
_apt_current_distros: |-
  {{
    apt__distro_aliases.values() | ansible.builtin.difference(['sid']) +
    _apt_current_ubuntu_distros
  }}

apt__distro_is_current: |-
  {{ apt__distro_name in _apt_current_distros }}

apt__distro_is_released: |-
  {{
    apt__distro_ver is version('1', 'ge') and
    apt__distro_ver is version('999', 'lt')
  }}

apt__distro_has_security: |-
  {{
    (apt__distro_ver is version('2.1', 'ge') and not apt__distro_is_unstable)
    or apt__vendor == 'ubuntu'
  }}

apt__distro_has_updates: |-
  {{ apt__distro_is_current }}

apt__distro_has_proposed_updates: |-
  {{ apt__distro_is_current }}

apt__distro_has_backports: |-
  {{
    (apt__distro_ver is version('12', 'ge') and not apt__distro_is_unstable)
    or apt__vendor == 'ubuntu'
  }}

apt__python3_is_default: |-
  {{
    apt__distro_ver is version('18.04', 'gt')
    if apt__vendor == 'ubuntu' else
    apt__distro_ver is version('11', 'ge')
  }}

## Computed defaults based on user-defined `apt__distro`.

apt__default_security_distro: |-
  {{
    apt__distro + (
      '-security' if (
        apt__distro_ver is version('11', 'ge') or apt__vendor == 'ubuntu'
      ) else '/updates'
    )
  }}

apt__default_updates_distro: '{{ apt__distro }}-updates'

apt__default_prop_updates_distro: |-
  {{
    apt__distro + (
      '-proposed-updates' if apt__vendor == 'debian' else '-proposed'
    )
  }}

apt__default_backports_distro: '{{ apt__distro }}-backports'

apt__default_mirror: |-
  {{
    (
      'http://archive.ubuntu.com/ubuntu/'
      if apt__distro_is_current else
      'http://old-releases.ubuntu.com/ubuntu/'
    ) if apt__vendor == 'ubuntu' else (
      'http://deb.debian.org/debian/'
      if apt__distro_is_current or apt__distro_is_unstable else
      'http://archive.debian.org/debian/'
    )
  }}

apt__default_security_mirror: |-
  {{
    (
      'http://security.ubuntu.com/ubuntu/'
      if apt__distro_is_current else
      'http://old-releases.ubuntu.com/ubuntu/'
    ) if apt__vendor == 'ubuntu' else (
      'http://security.debian.org/debian-security/'
      if apt__distro_is_current else
      'http://archive.debian.org/debian-security/'
    )
  }}

apt__default_updates_mirror: '{{ apt__mirror }}'

apt__default_prop_updates_mirror: '{{ apt__mirror }}'

apt__default_backports_mirror: '{{ apt__mirror }}'

apt__default_components: |-
  {{
    ['main',  'universe',  'restricted',  'multiverse']
    if apt__vendor == 'ubuntu' else
    ['main', 'contrib', 'non-free', 'non-free-firmware']
    if apt__distro_ver is version('12', 'ge') else
    ['main', 'contrib', 'non-free']
  }}
