---
# vim:ts=2:sw=2:et:ai:sts=2

# Process output of `named -v`.
_sbind_version: |-
  {{
    (
      (
        _sbind_chkver.stdout |
        ansible.builtin.regex_search('^BIND (\S+) .*', '\1', multiline=True)
      ) or ['0.0~invalid']
    ) | first
  }}
_sbind_has_9_13: |-
  {{ _sbind_version is ansible.builtin.version('9.13.0', 'ge') }}

_sbind_term:
  primary: |-
    {{ 'primary' if _sbind_has_9_13 else 'master' }}
  secondary: |-
    {{ 'secondary' if _sbind_has_9_13 else 'slave' }}
  primaries: |-
    {{ 'primaries' if _sbind_has_9_13 else 'masters' }}

# Find service name.
_sbind_svcnames:
  - bind9.service
  - named.service
_sbind_svcname: |-
  {{
    _sbind_svcnames |
    select('in', ansible_facts.services) |
    first |
    default('named')
  }}

# Pre-process configuration options.

_sbind_confdir: |-
  {{ simple_bind__config_dir or '/etc/bind' }}

_sbind_listen: |-
  {% set sections = ('listen_on', 'listen_on_v6') %}
  {% set result = dict(sections | zip(([], []))) %}
  {% for section in sections %}
  {% set opt = (simple_bind__options or {}).get(section) or [] %}
  {% set opt = [opt] if opt is not iterable or opt is string else opt %}
  {% for item in opt | select %}
  {% set item = item if item is mapping else dict(match_list=item) %}
  {% set port = item.get('port') or 53 %}
  {% set match_list = item.get('match_list') %}
  {% set match_list =
    ['any'] if not match_list else
    [match_list]
    if match_list is not iterable or match_list is string else
    match_list
  %}
  {% set _ = result[section].append(
      item | combine({'port': port, 'match_list': match_list})) %}
  {% endfor %}
  {% endfor %}
  {{- result }}

_sbind_ports: |-
  {{ _sbind_listen.values() | sum(start=[]) | map(attribute='port') | unique }}

_sbind_includes_always:
  - named.conf.options
  - named.conf.local
_sbind_includes: |-
  {{ _sbind_includes_always + (simple_bind__includes or []) }}

_sbind_zone_files: |-
  {% set result = [] %}
  {% for conf in simple_bind__primary_zones or [] %}
  {% set zone = conf.zone | mandatory('missing zone name') %}
  {% set view = conf.view | mandatory('missing view name') %}
  {% set dest =
    (_sbind_confdir, view, 'db.' + zone) | ansible.builtin.path_join
  %}
  {% set src = conf.src | mandatory('missing zone source') %}
  {% set src_type = conf.get('src_type') or 'string' %}
  {% set _ =
    ('ok' if src_type in ('template', 'file', 'string')) |
    mandatory('invalid source type: ' + src_type)
  %}
  {% set tmplvars =
    {
      'ZONE': zone if zone.endswith('.') else zone + '.',
      'VIEW': view,
    } | combine(conf.get('template_vars') or {})
  %}
  {% set content =
    lookup('file', src, rstrip=false)
    if src_type == 'file' else
    lookup('template', src, template_vars=tmplvars)
    if src_type == 'template' else
    src
  %}
  {% set _ = result.append(dict(dest=dest, content=content)) %}
  {% endfor %}
  {{- result -}}

_sbind_zone_dirs: |-
  {{
    _sbind_zone_files |
    map(attribute='dest') |
    map('ansible.builtin.dirname') |
    unique
  }}
