# vim:ts=2:sw=2:et:ai:sts=2
---
- name: _tina_reconfigure_network
  ansible.builtin.shell:  # noqa: risky-shell-pipe
    cmd: >-
      networkctl reload;
      ifdown --verbose --all --force;
      for dev in `ls /sys/class/net`; do
        ip link set dev $dev down;
      done;
      udevadm control --reload;
      udevadm trigger --action add --subsystem-match net;
      ip addr flush scope global;
      ifup --verbose --all --force;
  changed_when: true

- name: _tina_update_initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u -k all
  changed_when: true
