# vim: sw=2:sts=2
---

- name: Install package
  ansible.builtin.package:
    name: bind9
    state: present

- name: Find installed version
  ansible.builtin.command:
    argv: [/usr/sbin/named, -v]
  register: _sbind_chkver
  changed_when: false
  # Run normally even in check mode.
  check_mode: false

- name: Install configuration files
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ _sbind_confdir }}/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - named.conf
    - named.conf.options
    - named.conf.local
  notify:
    - _tina_validate_bind_conf
    - _tina_reload_bind

- name: Create view directories for zone files
  ansible.builtin.file:
    state: directory
    dest: '{{ item }}'
    owner: root
    group: root
    mode: '0755'
  loop: '{{ _sbind_zone_dirs }}'

- name: Install zone files
  ansible.builtin.copy:
    content: '{{ item.content }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ _sbind_zone_files }}'
  notify:
    - _tina_validate_bind_conf
    - _tina_reload_bind

- name: Install ferm configuration
  ansible.builtin.include_role:
    name: ferm_svc
  vars:
    ferm_svc__name: bind
    ferm_svc__allow_protos: [tcp, udp]
    ferm_svc__allow_from: '{{ simple_bind__ferm_allow_from }}'
    ferm_svc__allow_ports: '{{ _sbind_ports }}'
  when: simple_bind__install_ferm_svc | bool

- name: Populate service facts
  ansible.builtin.service_facts:
  # Run normally even in check mode.
  check_mode: false

- name: Start and enable service
  ansible.builtin.service:
    name: '{{ _sbind_svcname }}'
    state: started
    enabled: true
