# vim: sw=2:sts=2
---

- name: Install package
  ansible.builtin.package:
    name: bind9
    state: present

- name: Find installed version
  ansible.builtin.command:
    argv: [/usr/sbin/named, -v]
  register: _sbind_chkver
  changed_when: false
  # Run normally even in check mode.
  check_mode: false

- name: Install configuration files
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: /etc/bind/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - named.conf
    - named.conf.options
    - named.conf.local
  notify:
    - _tina_validate_bind_conf
    - _tina_reload_bind

- name: Place ferm config file
  ansible.builtin.template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.d/bind.conf
    owner: root
    group: adm
    mode: '0644'
  notify: _tina_reload_ferm
  when: simple_bind__install_ferm_svc | bool

- name: Populate service facts
  ansible.builtin.service_facts:
  # Run normally even in check mode.
  check_mode: false

- name: Start and enable service
  ansible.builtin.service:
    name: '{{ _sbind_svcname }}'
    state: started
    enabled: true
