# vim:ts=2:sw=2:et:ai:sts=2
---

- name: ensure ifupdown is present
  ansible.builtin.apt:
    name: ifupdown
    state: present

- name: gather facts about services
  ansible.builtin.service_facts:
  # Run normally even in check mode.
  check_mode: false
  when: ansible_service_mgr == 'systemd'

- name: stop and disable conflicting services
  ansible.builtin.service:
    name: '{{ item }}'
    state: stopped
    enabled: false
    masked: true
  when: ansible_service_mgr == 'systemd' and item in services
  with_items:
    - systemd-network-generator.service
    - systemd-networkd.service
  notify: _tina_reconfigure_network

- name: create udev persistent rules
  ansible.builtin.template:
    src: 70-persistent-net.rules.j2
    dest: /etc/udev/rules.d/70-persistent-net.rules
    owner: root
    group: root
    mode: '0644'
  notify: _tina_restart_all
  when: net__use_udev_persistent_rules | bool

- name: configure interfaces
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify: _tina_reconfigure_network
  when: net__interfaces

- name: apply configuration
  ansible.builtin.meta: flush_handlers
