# vim:ts=2:sw=2:et:ai:sts=2
---
- name: install node_exporter
  package:
    name: prometheus-node-exporter
    state: latest

- name: find installed version
  shell: >-
    (prometheus-node-exporter --version 2>&1 || echo "unknown version 0.0") |
    sed -n 's/.* version \([0-9.]\+[0-9]\).*/\1/p'
  register: node_exporter__version_check
  changed_when: False

- name: find installed version
  set_fact:
    node_exporter__version: '{{ node_exporter__version_check.stdout | d("0") }}'

- name: configure node_exporter
  template:
    src: default.j2
    dest: /etc/default/prometheus-node-exporter
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: start and enable service
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: install ferm configuration
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.d/prometheus-node-exporter.conf
    owner: root
    group: root
    mode: 0644
  notify: reload ferm
  when: node_exporter__install_ferm_svc | bool
