# vim:ts=2:sw=2:et:ai:sts=2
---

- name: install fail2ban and dependencies
  package:
    name:
      - fail2ban
      - python3-pyinotify
      - python3-systemd
    state: latest

- name: start and enable service
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: place jail configuration file
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: fail2ban__restart_fail2ban

- name: place path overrides configuration file
  template:
    src: paths-overrides.local.j2
    dest: /etc/fail2ban/paths-overrides.local
    owner: root
    group: root
    mode: 0644
  notify: fail2ban__restart_fail2ban

- name: place iptables action configuration file
  template:
    src: iptables.local.j2
    dest: /etc/fail2ban/action.d/iptables.local
    owner: root
    group: root
    mode: 0644
  notify: fail2ban__restart_fail2ban

- name: place ferm config file
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.d/fail2ban.conf
    owner: root
    group: adm
    mode: 0644
  notify: fail2ban__reload_ferm
  when: fail2ban__install_ferm_svc | bool
