# vim:ts=2:sw=2:et:ai:sts=2
---

thelounge__port: 9000
thelounge__reverse_proxy: false
thelounge__https_enable: false
thelounge__https_key: ''
thelounge__https_certificate: ''
thelounge__prefetch: false
thelounge__prefetch_storage: false
thelounge__file_upload_enable: false
thelounge__defaults_join: '#thelounge'

thelounge__ldap_enable: false
thelounge__ldap_url: ldaps://example.com
thelounge__ldap_primary_key: uid

# If true, install ferm configuration file.
thelounge__install_ferm_svc: false
# Optionally limit access by a list of IP addresses/blocks.
thelounge__ferm_allow_from: ~
