# vim:ts=2:sw=2:et:ai:sts=2
---
- name: preseed debconf
  debconf:
    name: ferm
    question: ferm/enable
    value: 'yes'
    vtype: boolean
  changed_when: False

- name: install package
  apt:
    name: [ferm, libnet-dns-perl]
    state: latest

- name: find installed version
  shell: >-
    /usr/sbin/ferm --version | sed -n 's/^ferm \([0-9].*\)/\1/p'
  register: ferm__version_check
  changed_when: False
  # Run normally even in check mode.
  check_mode: no

- name: find installed version
  set_fact:
    ferm__version: '{{ ferm__version_check.stdout | d("0") }}'
  # Run normally even in check mode.
  check_mode: no

- name: disable caching
  lineinfile:
    dest: /etc/default/ferm
    line: 'CACHE=no'
    regexp: '^CACHE[ =]'
    state: 'present'
  notify: ferm__reload_ferm

- name: create ferm.d directory
  file:
    path: /etc/ferm/ferm.d
    state: directory
    owner: root
    group: adm
    mode: 02750

- name: place main config file
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.conf
    owner: root
    group: adm
    mode: 0644
  notify: ferm__reload_ferm

- name: place service config files
  template:
    src: service.conf.j2
    dest: /etc/ferm/ferm.d/svc-{{ item.key }}.conf
    owner: root
    group: adm
    mode: 0644
  notify: ferm__reload_ferm
  with_dict: '{{ ferm__services }}'

- name: find obsolete service config files
  shell: >-
    ls /etc/ferm/ferm.d/ |
    sed -n 's/^svc-\(.*\)\.conf$/\1/p'
  register: ferm__config_files
  changed_when: False
  check_mode: no

- name: remove obsolete service config files
  file:
    path: /etc/ferm/ferm.d/svc-{{ item }}.conf
    state: absent
  with_items: '{{ ferm__config_files.stdout_lines }}'
  when: item not in ferm__services
  notify: ferm__reload_ferm

- name: place custom config files
  copy:
    content: '{{ item.value }}'
    dest: /etc/ferm/ferm.d/custom-{{ item.key }}.conf
    owner: root
    group: adm
    mode: 0644
  notify: ferm__reload_ferm
  with_dict: '{{ ferm__custom_configs }}'

- name: find obsolete custom config files
  shell: >-
    ls /etc/ferm/ferm.d/ |
    sed -n 's/^custom-\(.*\)\.conf$/\1/p'
  register: ferm__config_files
  changed_when: False
  check_mode: no

- name: remove obsolete custom config files
  file:
    path: /etc/ferm/ferm.d/custom-{{ item }}.conf
    state: absent
  with_items: '{{ ferm__config_files.stdout_lines }}'
  when: item not in ferm__custom_configs
  notify: ferm__reload_ferm

- name: place blacklist config file
  copy:
    dest: /etc/ferm/ferm.d/00-blacklist.conf
    owner: root
    group: adm
    mode: 0644
    content: |
      domain (ip ip6) table filter chain blacklist
          saddr @ipfilter(({{ saddr }}))
          REJECT;
  notify: ferm__reload_ferm
  when: ferm__blacklist is defined and ferm__blacklist
  vars:
    saddr: >-
      {{ ferm__blacklist if ferm__blacklist is string else
        ferm__blacklist | join(' ') }}

- name: start and enable service
  service:
    name: ferm
    state: started
    enabled: yes
