# vim:ts=2:sw=2:et:ai:sts=2
---
- name: _tina_restart_prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: _tina_reload_prometheus
  ansible.builtin.service:
    name: prometheus
    state: reloaded

- name: _tina_reload_ferm
  ansible.builtin.service:
    name: ferm
    state: reloaded
