# vim:ts=2:sw=2:et:ai:sts=2
---
- name: _tina_reload_postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: _tina_reload_sshd
  ansible.builtin.service:
    name: sshd
    state: reloaded

- name: _tina_reconfigure_locales
  ansible.builtin.shell:
    cmd: >-
      rm -f /etc/default/locale /etc/locale.gen &&
      dpkg-reconfigure -f noninteractive locales
  changed_when: true
