# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
---
- name: Create molecule hosts
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create container
      loop: '{{ molecule_yml.platforms }}'
      community.docker.docker_container:
        name: '{{ item.name }}'
        image: '{{ item.image }}'
        state: started
        command: sleep 1d  # TODO: run systemd
