---
platforms:
  - name: bookworm-tinapm
    image: geerlingguy/docker-debian12-ansible

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../..
  config_options:
    defaults:
      stdout_callback: debug
      stderr_callback: debug
  inventory:
    group_vars:
      all:
        ansible_connection: community.docker.docker
