# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/molecule/main/src/molecule/data/molecule.json
---
dependency:
  name: shell
  command: pip install toml
driver:
  name: docker
platforms:
  - name: tinapm-bookworm
    image: tinapm:bookworm
    pre_build_image: false
    override_command: false
    privileged: true  # FIXME: :'-(

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  config_options:
    defaults:
      stdout_callback: ansible.posix.debug
      stderr_callback: ansible.posix.debug
  inventory:
    group_vars:
      all:
        ansible_connection: community.docker.docker
