# vim:ts=2:sw=2:et:ai:sts=2
---
# This task file is executed in a loop over users__create_users.

- name: '[{{ user.name }}] create user'
  ansible.builtin.user:
    state: present
    system: '{{ user.system }}'
    name: '{{ user.name }}'
    comment: '{{ user.gecos }}'
    password: '{{ user.password }}'
    groups: '{{
      user.groups if user.groups is string else ",".join(user.groups) }}'
    append: '{{ user.append }}'
    home: '{{ user.home }}'
    create_home: '{{ user.create_home }}'
    move_home: '{{ user.move_home }}'
    shell: '{{ user.shell }}'
    generate_ssh_key: '{{ user.generate_ssh_key }}'
    update_password: '{{ user.update_password }}'

- name: '[{{ user.name }}] set mail forwarding'
  ansible.builtin.lineinfile:
    dest: /etc/aliases
    line: '{{ user.name }}: {{ user.forward }}'
    regexp: '^{{ user.name }}:.*'
    state: '{{ "present" if user.forward else "absent" }}'
  notify: _tina_run_newaliases

- name: '[{{ user.name }}] set SSH authorized keys'
  ansible.posix.authorized_key:
    user: '{{ user.name }}'
    key: |
      {{
        user.authorized if user.authorized is string else
        '\n'.join(user.authorized)
      }}
      "\n".join(user.authorized)
      }}'
    exclusive: true

- name: '[{{ user.name }}] set-up user home: directories'
  ansible.builtin.file:
    path: '{{ user.home }}/{{ item.path }}'
    mode: '{{ item.mode }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    state: directory
  with_community.general.filetree: '{{
    users__home_dir_templates }}/{{ user.name }}'
  when: item.state == 'directory'

- name: '[{{ user.name }}] set-up user home: normal files'
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ user.home }}/{{ item.path }}'
    mode: '{{ item.mode }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
  with_community.general.filetree: '{{
    users__home_dir_templates }}/{{ user.name }}'
  when: item.state == 'file' and not item.src.endswith('.j2')

- name: '[{{ user.name }}] set-up user home: templates'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ user.home }}/{{ item.path | regex_replace("\.j2$", "") }}'
    mode: '{{ item.mode }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
  with_community.general.filetree: '{{
    users__home_dir_templates }}/{{ user.name }}'
  when: item.state == 'file' and item.src.endswith('.j2')

- name: '[{{ user.name }}] set-up user home: symlinks'
  ansible.builtin.file:
    src: '{{ item.src }}'
    path: '{{ user.home }}/{{ item.path }}'
    mode: '{{ item.mode }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    state: link
    force: true
    follow: false
  with_community.general.filetree: '{{
    users__home_dir_templates }}/{{ user.name }}'
  when: item.state == 'link'
