# vim:ts=2:sw=2:et:ai:sts=2
---
- name: Install package
  ansible.builtin.package:
    name: prometheus-blackbox-exporter
    state: present

- name: Configure probes
  ansible.builtin.template:
    src: blackbox.yml.j2
    dest: '{{ blackbox_exporter__config_file }}'
    owner: root
    group: root
    mode: '0644'
  notify: _tina_reload_blackbox_exporter

- name: Configure service
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/prometheus-blackbox-exporter
    owner: root
    group: root
    mode: '0644'
  notify: _tina_restart_blackbox_exporter

- name: Install ferm configuration
  ansible.builtin.include_role:
    name: ferm_svc
  vars:
    ferm_svc__name: prometheus-blackbox-exporter
    ferm_svc__allow_protos: tcp
    ferm_svc__allow_from: '{{ blackbox_exporter__ferm_allow_from }}'
    ferm_svc__allow_ports: '{{ blackbox_exporter__listen_port }}'
  when: blackbox_exporter__install_ferm_svc | bool

- name: Start and enable service
  ansible.builtin.service:
    name: prometheus-blackbox-exporter
    state: started
    enabled: true
