# vim:ts=2:sw=2:et:ai:sts=2
---
- name: Install mtail
  ansible.builtin.package:
    name: mtail
    state: present
  notify: _tina_restart_mtail

- name: Configure mtail
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/mtail
    owner: root
    group: root
    mode: '0644'
  notify: _tina_restart_mtail

- name: Install mtail programs
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/mtail/{{ item | basename }}
    owner: root
    group: root
    mode: '0644'
  notify: _tina_restart_mtail
  with_items: '{{ mtail__programs or [] }}'

- name: Start and enable service
  ansible.builtin.service:
    name: mtail
    state: started
    enabled: true

- name: Install ferm configuration
  ansible.builtin.template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.d/mtail.conf
    owner: root
    group: root
    mode: '0644'
  notify: _tina_reload_ferm
  when: mtail__install_ferm_svc | bool
