# vim: sw=2:sts=2
---

- name: Install required packages
  ansible.builtin.package:
    name:
      - thelounge
      - acl
    state: present

- name: Set up SSL certificate ACL
  ansible.builtin.include_tasks: ssl_certificate_acl.yaml
  loop:
    - '{{ thelounge__https_key }}'
    - '{{ thelounge__https_certificate }}'
  when:
    - thelounge__https_key != ''
    - thelounge__https_certificate != ''

- name: Configure TheLounge
  ansible.builtin.template:
    src: config.js.j2
    dest: /etc/thelounge/config.js
    owner: thelounge
    group: thelounge
    mode: '0660'
  notify: _tina_pm_restart_thelounge

- name: Install ferm configuration
  ansible.builtin.include_role:
    name: ferm_svc
  vars:
    ferm_svc__name: thelounge
    ferm_svc__allow_protos: tcp
    ferm_svc__allow_from: '{{ thelounge__ferm_allow_from }}'
    ferm_svc__allow_ports: '{{ thelounge__port }}'
  when: thelounge__install_ferm_svc | bool

- name: Start and enable TheLounge service
  ansible.builtin.service:
    name: thelounge
    state: started
    enabled: true
