# vim:ts=2:sw=2:et:ai:sts=2
---

node_exporter__listen_addr: ''
node_exporter__listen_port: 9100
node_exporter__disk_ignored_devs:
node_exporter__fs_ignored_mounts: '^/(sys|proc|dev|run)($|/)'
node_exporter__net_ignored_devs: '^lo$'
node_exporter__enabled_collectors:
node_exporter__extra_args:

# If true, install ferm configuration file.
node_exporter__install_ferm_svc: false
# Optionally limit access by a list of IP addresses/blocks.
node_exporter__ferm_allow_from: ~
