# vim:ts=2:sw=2:et:ai:sts=2
---
- name: install prometheus
  package:
    name: prometheus
    state: latest

- name: configure prometheus cmdline
  template:
    src: default.j2
    dest: /etc/default/prometheus
    owner: root
    group: root
    mode: 0644
  notify: prometheus__restart_prometheus

- name: create rules directory
  file:
    path: /etc/prometheus/rules
    state: directory
    owner: root
    group: root
    mode: 0755

- name: install rules files
  copy:
    src: '{{ item }}'
    dest: '/etc/prometheus/rules/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
    validate: /usr/bin/promtool check rules %s
  notify: prometheus__reload_prometheus
  with_items: '{{ prometheus__rules }}'
  when: not item.endswith('.j2')

- name: install rules templates
  template:
    src: '{{ item }}'
    dest: '/etc/prometheus/rules/{{
      item | basename | regex_replace("\.j2$", "") }}'
    # Avoid clashes with prometheus template language.
    variable_start_string: '{='
    variable_end_string: '=}'
    owner: root
    group: root
    mode: 0644
    validate: /usr/bin/promtool check rules %s
  notify: prometheus__reload_prometheus
  with_items: '{{ prometheus__rules }}'
  when: item.endswith('.j2')

- name: configure prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: 0644
    validate: /usr/bin/promtool check config %s
  notify: prometheus__reload_prometheus

- name: start and enable service
  service:
    name: prometheus
    state: started
    enabled: yes

- name: install ferm configuration
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.d/prometheus.conf
    owner: root
    group: adm
    mode: 0644
  notify: prometheus__reload_ferm
  when: prometheus__install_ferm_svc | bool
