# vim:ts=2:sw=2:et:ai:sts=2
---
- name: reload udev
  service:
    name: udev
    state: reloaded
  listen: reload udev and reconfigure network

- name: reconfigure network
  command:
    cmd: |
      bash -c '
        ifdown --all --force;
        for dev in `ip -o link show | sed -n "s/[0-9]*: \(\S\+\):.*/\1/p"`; do
          ip link set dev $dev down;
        done;
        udevadm trigger -c add -s net;
        ip addr flush scope global;
        ifup --all --force;
      '
  listen: reload udev and reconfigure network
