# vim:ts=2:sw=2:et:ai:sts=2
---
- name: net__restart_udev
  ansible.builtin.service:
    name: udev
    state: restarted
  listen: net__restart_all

- name: net__reconfigure_network
  ansible.builtin.shell:
    cmd: >-
      ifdown --all --force;
      for dev in `ip -o link show | sed -n 's/[0-9]*: \(\S\+\):.*/\1/p'`; do
        ip link set dev $dev down;
      done;
      udevadm trigger -c add -s net;
      ip addr flush scope global;
      ifup --all --force;
  listen: net__restart_all
