# vim:ts=2:sw=2:et:ai:sts=2
---

prometheus__listen_port: 9090
prometheus__listen_addr:
prometheus__retention_time:
prometheus__retention_size:
prometheus__external_url:
prometheus__extra_args:
prometheus__install_ferm_svc: false
prometheus__allow_from:

prometheus__monitored_nodes: []
prometheus__scrape_configs: []

prometheus__rules: []
prometheus__alertmanagers: []
prometheus__monitored_prometheus: []
prometheus__federated_prometheus: []
# Only import metrics that have a ':' in their name (derived from explicit
# rules), or the special up metric.
prometheus__federate_filter:
  - '{__name__=~".+:.+"}'
  - '{job="prometheus"}'
  - up
