# vim:ts=2:sw=2:et:ai:sts=2
---
- name: check cloud-init presence
  stat:
    path: /etc/cloud/cloud.cfg
  register: _cloud_init_cfg
  when: base_setup__disable_cloud_init | bool
  check_mode: false

- name: disable cloud-init
  file:
    path: /etc/cloud/cloud-init.disabled
    state: touch
    modification_time: preserve
    access_time: preserve
  when: base_setup__disable_cloud_init | bool and _cloud_init_cfg.stat.exists

# Avoid `systemd` strategy as we might not have dbus yet.
- name: set hostname
  hostname:
    name: '{{ _base_setup__hostname_short }}'
    use: debian
  when: base_setup__set_hostname

- name: set FDQN
  lineinfile:
    dest: /etc/hosts
    line: |-
      127.0.1.1 {{ base_setup__set_hostname }} {{ _base_setup__hostname_short }}
    regexp: '^127\.0\.1\.1\s'
    insertafter: '^127\.0\.0\.1'
    state: present
  when: base_setup__set_hostname

- name: setup APT, upgrade installed packages, and install base packages
  include_role:
    name: apt
  vars:
    apt__run_upgrade: true
    apt__run_autoremove: true
    apt__purge_removed: true
    apt__packages_to_install: '{{ _base_setup__pkg_install }}'
    apt__services_to_enable: '{{ _base_setup__svc_enable_start }}'
    apt__services_to_start: '{{ _base_setup__svc_enable_start }}'

- name: set mail relay
  lineinfile:
    dest: /etc/postfix/main.cf
    line: 'relayhost = {{ base_setup__mail_relay }}'
    regexp: '^relayhost\s*='
    insertafter: '^\s*#relayhost'
    state: present
  when: base_setup__mail_relay and base_setup__setup_postfix
  notify: base_setup__reload_postfix

- name: 'set-up sudoers: sudo group'
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo\s'
    line: '%sudo ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  when: base_setup__setup_sudo

- name: set defaults for bash
  template:
    src: bash.bashrc.j2
    dest: /etc/bash.bashrc
