# vim:ts=2:sw=2:et:ai:sts=2
---
- name: check cloud-init presence
  stat:
    path: /etc/cloud/cloud.cfg
  register: _cloud_init_cfg
  when: base_setup__disable_cloud_init | bool

- name: disable cloud-init
  file:
    path: /etc/cloud/cloud-init.disabled
    state: touch
    modification_time: preserve
    access_time: preserve
  when: base_setup__disable_cloud_init | bool and _cloud_init_cfg.stat.exists

- name: set hostname
  hostname:
    name: '{{ _hostname_short }}'
  when: base_setup__set_hostname and _hostname_short

- name: set FDQN
  lineinfile:
    dest: /etc/hosts
    line: 127.0.1.1 {{ base_setup__set_hostname }} {{ _hostname_short }}
    regexp: '^127\.0\.1\.1\s'
    insertafter: '^127\.0\.0\.1'
    state: present
  when: base_setup__set_hostname and _hostname_short

- name: setup APT, upgrade installed packages, and install base packages
  include_role:
    name: apt
  vars:
    apt__run_upgrade: true
    apt__run_autoremove: true
    apt__purge_removed: true
    apt__packages_to_install: '{{
      ["postfix", "sudo"] +
      base_setup__pkg_install | d([])
      }}'
    apt__services_to_enable: '{{
      ["postfix"] +
      base_setup__svc_enable_start | d([])
      }}'
    apt__services_to_start: '{{
      ["postfix"] +
      base_setup__svc_enable_start | d([])
      }}'

- name: set mail relay
  lineinfile:
    dest: /etc/postfix/main.cf
    line: 'relayhost = {{ base_setup__mail_relay }}'
    regexp: '^relayhost\s*='
    insertafter: '^#relayhost'
    state: present
  when: base_setup__mail_relay is defined and base_setup__mail_relay
  notify: reload postfix

- name: bash defaults
  template:
    src: bash.bashrc.j2
    dest: /etc/bash.bashrc

- name: 'set-up sudoers: sudo group'
  lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo\s'
      line: '%sudo ALL=(ALL) ALL'
      validate: 'visudo -cf %s'

- name: 'set-up sudoers: sudo-nopw group'
  lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo-nopw\s'
      line: '%sudo-nopw ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

#- name: 'set-up sudoers: notty'
#  # This is needed for pipelining, rsync, etc.
#  lineinfile:
#      dest: /etc/sudoers
#      state: absent
#      regexp: '^Defaults\s+requiretty'
#      validate: 'visudo -cf %s'

- name: create users
  include_role:
    name: users
