---
name: molecule

on:
  pull_request:
  push:
    branches:
      - main
      - force_ci/molecule/**  # For development/debugging of the workflow.

permissions:
  contents: read
  pull-requests: write

jobs:
  molecule:
    name: Molecule tests
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
